import * as yup from "yup";

export interface User {
  id: number;
  username: string;
  email: string;
  name: string;
  password: string;
  role: string;
  deleted_at?: null | string | Date;
}

export interface UserDetail extends User {}

export const userSchema = yup.object().shape({
  username: yup.string().required("Vui lòng nhập username"),
  email: yup
    .string()
    .email("Vui lòng nhập đúng định dạng email")
    .required("Vui lòng nhập username"),
  name: yup.string().required("Vui lòng nhập name"),
  password: yup.string().required("Vui lòng nhập password"),
});

export const initialUser: UserDetail = {
  id: 0,
  username: "",
  email: "",
  name: "",
  password: "",
  role: "",
};

export const users: UserDetail[] = [
  {
    id: 10,
    username: "username 1",
    email: "email 1",
    name: "name 1",
    password: "password 1",
    role: "role 1",
    deleted_at: null,
  },
  {
    id: 20,
    username: "username 2",
    email: "email 2",
    name: "name 2",
    password: "password 2",
    role: "role 2",
    deleted_at: null,
  },
  {
    id: 30,
    username: "username 3",
    email: "email 3",
    name: "name 3",
    password: "password 3",
    role: "role 3",
    deleted_at: null,
  },
  {
    id: 40,
    username: "username 4",
    email: "email 4",
    name: "name 4",
    password: "password 4",
    role: "role 4",
    deleted_at: null,
  },
  {
    id: 50,
    username: "username 5",
    email: "email 5",
    name: "name 5",
    password: "password 5",
    role: "role 5",
    deleted_at: null,
  },
  {
    id: 60,
    username: "username 6",
    email: "email 6",
    name: "name 6",
    password: "password 6",
    role: "role 6",
    deleted_at: null,
  },
  {
    id: 70,
    username: "username 7",
    email: "email 7",
    name: "name 7",
    password: "password 7",
    role: "role 7",
    deleted_at: null,
  },
  {
    id: 80,
    username: "username 8",
    email: "email 8",
    name: "name 8",
    password: "password 8",
    role: "role 8",
    deleted_at: null,
  },
  {
    id: 90,
    username: "username 9",
    email: "email 9",
    name: "name 9",
    password: "password 9",
    role: "role 9",
    deleted_at: null,
  },
  {
    id: 100,
    username: "username 10",
    email: "email 10",
    name: "name 10",
    password: "password 10",
    role: "role 10",
    deleted_at: null,
  },
  {
    id: 110,
    username: "username 11",
    email: "email 11",
    name: "name 11",
    password: "password 11",
    role: "role 11",
    deleted_at: null,
  },
  {
    id: 120,
    username: "username 12",
    email: "email 12",
    name: "name 12",
    password: "password 12",
    role: "role 12",
    deleted_at: null,
  },
  {
    id: 130,
    username: "username 13",
    email: "email 13",
    name: "name 13",
    password: "password 13",
    role: "role 13",
    deleted_at: null,
  },
  {
    id: 140,
    username: "username 14",
    email: "email 14",
    name: "name 14",
    password: "password 14",
    role: "role 14",
    deleted_at: null,
  },
  {
    id: 150,
    username: "username 15",
    email: "email 15",
    name: "name 15",
    password: "password 15",
    role: "role 15",
    deleted_at: null,
  },
  {
    id: 160,
    username: "username 16",
    email: "email 16",
    name: "name 16",
    password: "password 16",
    role: "role 16",
    deleted_at: null,
  },
  {
    id: 170,
    username: "username 17",
    email: "email 17",
    name: "name 17",
    password: "password 17",
    role: "role 17",
    deleted_at: null,
  },
  {
    id: 180,
    username: "username 18",
    email: "email 18",
    name: "name 18",
    password: "password 18",
    role: "role 18",
    deleted_at: null,
  },
  {
    id: 190,
    username: "username 19",
    email: "email 19",
    name: "name 19",
    password: "password 19",
    role: "role 19",
    deleted_at: null,
  },
  {
    id: 200,
    username: "username 20",
    email: "email 20",
    name: "name 20",
    password: "password 20",
    role: "role 20",
    deleted_at: null,
  },
  {
    id: 210,
    username: "username 21",
    email: "email 21",
    name: "name 21",
    password: "password 21",
    role: "role 21",
    deleted_at: null,
  },
  {
    id: 220,
    username: "username 22",
    email: "email 22",
    name: "name 22",
    password: "password 22",
    role: "role 22",
    deleted_at: null,
  },
  {
    id: 230,
    username: "username 23",
    email: "email 23",
    name: "name 23",
    password: "password 23",
    role: "role 23",
    deleted_at: null,
  },
  {
    id: 240,
    username: "username 24",
    email: "email 24",
    name: "name 24",
    password: "password 24",
    role: "role 24",
    deleted_at: null,
  },
];
